feat(scripts) - pkg add provides subcommand

diff --git a/scripts/.local/bin/pkg b/scripts/.local/bin/pkg
--- a/scripts/.local/bin/pkg
+++ b/scripts/.local/bin/pkg
@@ -1,13 +1,19 @@
 #!/usr/bin/env bash
 set -e
 
+subcommand_error() {
+    echo "ERROR: subcommand not supported" 2>1
+    exit 1
+}
+
 parse_subcommands() {
     subcommand=""
     case "$1" in
-        info)    subcommand="info"    ;;
-        install) subcommand="install" ;;
-        search)  subcommand="search"  ;;
-        upgrade) subcommand="upgrade" ;;
+        info)     subcommand="info"    ;;
+        install)  subcommand="install" ;;
+        provides) subcommand="provides" ;;
+        search)   subcommand="search"  ;;
+        upgrade)  subcommand="upgrade" ;;
         *)
             echo "ERROR! : Unknown subcommand '$1'"
             exit 1 ;;
@@ -21,37 +27,41 @@ set_package_manager() {
         arch)
             package_manager() {
                 case "$subcommand" in
-                    info)         pacman -Si "${@:2}"  ;;
-                    install) sudo pacman -Sy "${@:2}"  ;;
-                    search)       pacman -Sys "${@:2}" ;;
-                    upgrade) sudo pacman -Syu          ;;
+                    info)          pacman -Si "${@:2}"  ;;
+                    install)  sudo pacman -Sy "${@:2}"  ;;
+                    provides)      pacman -Fy "${@:2}"  ;;
+                    search)        pacman -Sys "${@:2}" ;;
+                    upgrade)  sudo pacman -Syu          ;;
                 esac
             } ;;
         fedora)
             package_manager() {
                 case "$subcommand" in
-                    info)         dnf info "${@:2}"    ;;
-                    install) sudo dnf install "${@:2}" ;;
-                    search)       dnf search "${@:2}"  ;;
-                    upgrade) sudo dnf upgrade          ;;
+                    info)          dnf info "${@:2}"     ;;
+                    install)  sudo dnf install "${@:2}"  ;;
+                    provides)      dnf provides "${@:2}" ;;
+                    search)        dnf search "${@:2}"   ;;
+                    upgrade)  sudo dnf upgrade           ;;
                 esac
             } ;;
         opensuse-tumbelweed)
             package_manager() {
                 case "$subcommand" in
-                    info)         zypper info "${@:2}"    ;;
-                    install) sudo zypper install "${@:2}" ;;
-                    search)       zypper search "${@:2}"  ;;
-                    upgrade) sudo zypper update           ;;
+                    info)          zypper info "${@:2}"                 ;;
+                    install)  sudo zypper install "${@:2}"              ;;
+                    provides)      zypper search --provides -x "${@:2}" ;;
+                    search)        zypper search "${@:2}"               ;;
+                    upgrade)  sudo zypper update                        ;;
                 esac
             } ;;
         ubuntu)
             package_manager() {
                 case "$subcommand" in
-                    info)         apt info "${@:2}"              ;;
-                    install) sudo apt install "${@:2}"           ;;
-                    search)       apt search "${@:2}"            ;;
-                    upgrade) sudo apt update && sudo apt upgrade ;;
+                    info)          apt info "${@:2}"              ;;
+                    install)  sudo apt install "${@:2}"           ;;
+                    provides)      subcommand_error               ;;
+                    search)        apt search "${@:2}"            ;;
+                    upgrade)  sudo apt update && sudo apt upgrade ;;
                 esac
             } ;;
     esac
